name: generate user-statistician

on:
  schedule:
    - cron: '42 5 * * *'
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches: [ master ]
    paths: [ '.github/workflows/userstats.yml' ]

jobs:
  stats:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
      
    steps:
    - uses: actions/checkout@v4

    - name: Generate the user stats image for GitHub profile
      uses: cicirello/user-statistician@v1
      with:
        colors: dark-dimmed
        custom-title: My GitHub Statistics
        max-languages: 100
        animated-language-chart: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
